### ISSUE TITLE
parseAccept returns lowest-ranked language first

### ISSUE THREAD

**Issue by jbalogh** [auraphp/Aura.Web#1]
The docs and comments suggest parseAccept[1](https://github.com/auraphp/aura.web/blob/master/src/Context.php#L624) should return the highest-ranked language first, but it actually returns the languages in ascending order.

```
-        return $sorted;
+        return array_reverse($sorted);
```

**Comment by pmjones** [comment]
Fixed in https://github.com/auraphp/aura.web/commit/f1383ced3f3c2c24ece914d1b23709b54ca70683 -- thanks!
