### ISSUE TITLE
Redirect Stuff

### ISSUE THREAD

**Issue by harikt** [auraphp/Aura.Web#10]
We discussed about the redirecting from one action to another action .

http://colabti.org/irclogger/irclogger_log/auraphp?date=2012-08-14#l71

Two things I think I want to point out

1 ) The url will not change : 

That means if the user was at `post/add` and submit the data and we redirect to another page the url will be same as `post/add` .

2 ) The above brings another problem.  The main goal of the redirect from a post is not just to move to another page . It can also be to remove the second post on the same page . In this case if the user again clicks F5 its just doing another post , which is a wrong way

3 ) Consider a user trying to view an article say `hello-world`, and its only visible to users who are logged in . We move them to login page and finally how can we move them to the `hello-world` ?

**Comment by pmjones** [comment]
If I understand you correctly, there are two issues here.
1. Picking the proper URL to redirect to. I propose that this is not an issue that Aura.Web should handle; the framework-level controller has a router object, and we should use that to pick the right URL.
2. Clicking submit or refresh multiple times during a POST can cause trouble; this is why we have both Response::setRedirect() and setRedirectAfterPost(). Using the latter sets caching headers properly to help avoid that problem.

Regarding your point 3, you would need to pass along the "original" landing page somehow, either as a GET or POST param, or by storing it in a session segment.  The login controller can then look at the Context::getQuery() or getPost(), or at a session segment flash, and redirect to the original landing page.

Hope that all helps.

**Comment by harikt** [comment]
@pmjones Yes you are right . I didn't think about that time, and fixed it like 

```
$this->getResponse()->setRedirect(
    $this->router->generate('post_view', ['id' => $id])
);
```

in controller. But what about 

```
public function redirect($name, $params)
{
    if ( $name is url ) {
        $url = $name;
    } else {
        $url = $this->router->generate($name, $params);
    }
    $this->getResponse()->setRedirect( $uri );
}
```

in the `Aura.Framework` controller itself , so we can do $this->redirect( $path );

Thoughts ?
