### ISSUE TITLE
request content object checks CONTENT_TYPE but not HTTP_CONTENT_TYPE

### ISSUE THREAD

**Issue by harikt** [auraphp/Aura.Web#23]
Reporting for @garoevans for the issue reported via twitter https://twitter.com/garoevans/status/423782504794181632

> the request content object checks CONTENT_TYPE but not HTTP_CONTENT_TYPE. By design?

**Comment by garoevans** [comment]
Looking around some more it seems that is only part of the problem. When using the DI container to configure the content object the server array is passed with a key of 'server' nested:

https://github.com/auraphp/Aura.Web/blob/develop-2/config/default/define.php#L51:L53

In PHP terms this causes the following output when `var_dump`ing the `$server` variable inside the Request\Content is construct:

```
array(1) {
  ["server"]=>
  array(21) {
    ["DOCUMENT_ROOT"]=>
...
```

**Comment by harikt** [comment]
I feel this is not yet corrected in the built in php server. ( not talking about apache )

**Comment by pmjones** [comment]
Entirely possible that it's not fixed for PHP server.

**Comment by harikt** [comment]
@garoevans what version of PHP is yours? We have been discussing this over #24 .

**Comment by garoevans** [comment]
I'm running php5.5 but on my work laptop which is not with me at the
moment. I'll be updating the libraries on monday and will confirm if it's
fixed the way I was using it.

On 18 January 2014 15:51, Hari K T notifications@github.com wrote:

> @garoevans https://github.com/garoevans what version of PHP is yours?
> We have been discussing this over #24https://github.com/auraphp/Aura.Web/pull/24.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/auraphp/Aura.Web/issues/23#issuecomment-32684893
> .

## 

t: @garoevans
l: http://uk.linkedin.com/in/garoevans/
m: +44 7718 617228
