### ISSUE TITLE
$_SERVER['HTTP_CONTENT_TYPE']

### ISSUE THREAD

**Issue by jakeasmith** [auraphp/Aura.Web#31]
There is a bug in the built in PHP server that populates `$_SERVER['HTTP_CONTENT_TYPE']` instead of `$_SERVER['CONTENT_TYPE']`. In fact, you're the one who reported it :)

https://bugs.php.net/bug.php?id=66606&thanks=6

Would you accept a PR that checks for `$_SERVER['HTTP_CONTENT_TYPE']` and uses that when it exists?

**Comment by harikt** [comment]
:+1:  . I am recalling this bug. 

Do we really need to consider php server ? To me it is good to have a patch.

@pmjones travelling so you may hear after a few days. You can send a PR for considering in the mean time ( if you have some time).

Thanks.

**Comment by Bilge** [comment]
> Do we really need to consider php server ?

Yes.

**Comment by harikt** [comment]
Closing in favour of https://github.com/auraphp/Aura.Web/pull/32  being merged.

Re-open in-case things are not working.

Thank you.

**Comment by cordoval** [comment]
is coming up pretty good these kernels and project repos :+1:
