### ISSUE TITLE
[NFR] Aura\Web\Request\Values::getBoolean()

### ISSUE THREAD

**Issue by iansltx** [auraphp/Aura.Web#34]
I'm consuming "pseudo-boolean" values from the query string, which if not handled carefully runs into issues because `"false"` evaluates to `true`, so I have to do something like this:

``` php
// default to true if param not provided, run condition if false
if (in_array($request->query->get('param', 1), ['false', 0])) {
    ...
}
```

...and casting to boolean doesn't work for avoiding the above.

If anyone else has this issue/is interested in a fix, I'll build out and PR getBoolean() (getBool()?) so that instead we've got:

``` php
if (false === $request->query->getBoolean('param', true)) {
    ...
}
```

or

``` php
if (!$request->query->getBoolean('param', true)) {
    ...
}
```

with a default of `false` of the second argument isn't provided.

Anyone interested?

**Comment by harikt** [comment]
not sure whether this is to be in core. The query parameters is up-to the developers to handle properly is my current thought.

**Comment by pmjones** [comment]
I discussed this with @iansltx in person. I was originally against, but I can now see the benefits here. I will put up an experimental branch for this issue with getBool(), getInt(), and getFloat() implemented.
