### ISSUE TITLE
Serialize and Deserialize

### ISSUE THREAD

**Issue by harikt** [auraphp/Aura.Web#37]
Hi Paul, 

Do you think it is good to have a serialize and deserialize functionality in https://github.com/auraphp/Aura.Web/blob/develop-2/src/ResponseSender.php .

So it will implement http://php.net/manual/en/class.serializable.php

**Comment by pmjones** [comment]
/me furrows brow

Why would we want this?

**Comment by harikt** [comment]
I was thinking of caching the entire response :+1:  . May be you are against ;) .
