### ISSUE TITLE
Remove compact and make array

### ISSUE THREAD

**Issue by harikt** [auraphp/Aura.Web#43]
@TimeToogo I noticed the PR https://github.com/auraphp/Aura.Web/pull/41 works in some php versions but not for all. 

Sometimes 

`````` compact(
    '_ENV',
    '_GET',
    '_POST',
    '_COOKIE',
    '_SERVER'
)```

not getting the SERVER values. It seems good to make it as array with keys.

```php
array(
    '_ENV' => $_ENV,
    '_GET' => $_GET,
    '_POST' => $_POST,
    '_COOKIE' => $_COOKIE,
    '_SERVER' => $_SERVER
)
``````

**Comment by TimeToogo** [comment]
Interesting, I thought the above two would be identical. I ran the compact function across versions http://3v4l.org/7J896 but could not spot anything strange.

**Comment by harikt** [comment]
@TimeToogo Nice and Thanks. May be for I am using the php server not the apache ?
