### ISSUE TITLE
Bot and Mobile detection methods in Request object

### ISSUE THREAD

**Issue by jimbojsb** [auraphp/Aura.Web#47]
Hi all,

I recently was using `Aura\Web\Request` and noticed it has some methods for crawler and mobile device detection. While I'm sure these are useful to some, it sure seems like they are a bit out of place on this object. It seems to me this is a case of "trying to do too much". There are also other great libraries out there like MobileDetect that can do this way more accurately. 

There is no actual bug here, just wanted to point out something that I noticed that was in my opinion a little out of place.

**Comment by harikt** [comment]
Hi @jimbojsb , 
I hear your feedback, but I feel it is good / right place if a user need to know the details. May be it is not that perfect. In that case they can switch to any third party libraries out there. But I feel there is a cost for it.

**Comment by pmjones** [comment]
>  in my opinion a little out of place

/me nods

Yeah, that functionality has been in place for a long time (several years?) and I never stepped back to review its appropriateness. In a v3 release it would make sense to remove those functions to their own package, or perhaps remove them entirely in favor of an external library. Unfortunately I cannot remove it now, as that would be a BC break.
