### ISSUE TITLE
Is there a plan/timeline for compliance with PSR-7?

### ISSUE THREAD

**Issue by JordanRL** [auraphp/Aura.Web#50]
I just noticed that Aura.Router 3.x requires a Request object which implements the PSR-7 spec, but there isn't even a dev branch in Aura.Web for PSR-7 compliance. What's the plan here?

**Comment by harikt** [comment]
@JordanRL For the current time, you can use https://github.com/zendframework/zend-diactoros or any other implementations of PSR-7 .

**Comment by JordanRL** [comment]
So then, until Aura.Web moves over, you can choose either Aura.Web or Aura.Router, but not both?

**Comment by harikt** [comment]
@JordanRL not sure I get you.

You can use Aura.Router v2 and Aura.Web v2. 

You can also use Aura.Router v3 and Aura.Web v2 . If you are using Aura.Router v3 it have a dependency on psr-7 implementation. Aura at present don't have one ( don't know about future ) . So you need to use one of the psr-7 implementation.

If you are using psr-7 I am not sure why you need Aura.Web though. 

Hope that helps!

**Comment by pmjones** [comment]
@harikt has the right idea here.

The Aura 2.x router is completely independent of any particular Request implementation. You should be able to pull values from a PSR-7 request object, or any other request object, and feed them to the 2.x Router.

The Aura.3.x router does depend on a PSR-7 request interface, but is independent of any specific implementation; you can use whatever one you want there. The Zend Diactoros one seems reasonable. With a PSR-7 implementation, you don't really need Aura.Web 2.x any more (though Web 2.x does have some very nice convenience functionality).

I have it in the back of my mind to explore building an Aura.Web 3.x version as an implementation of PSR-7, but that's a high-effort task, and may not be worth my time when other no-dependency implementations available. However, if someone else wants to build one and submit it as a contribution, I'd be happy to talk about that.

@JordanRL does that help to explain the situation?

**Comment by pmjones** [comment]
This package, at least in its 2.x version, will not become PSR-7 compliant.

Further, given the difficulty (impossibility?) of implementing PSR-7 as written, I don't envision doing so in a future version either.

**Comment by proggeler** [comment]
If anyone still looking for a PSR-7 solution build on Aura.Web, I gave it a try:
[dmt-software/aura-web-psr](https://github.com/dmt-software/aura-web-psr)

This package might also help you to migrate to another PSR-7 implementation.
